# Generated by Django 4.2.2 on 2024-02-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
